TEXTS = {
    "en": {
        "welcome": "👋 Welcome to the Meetupshare Bot!\n\nThis bot helps you organize and participate in various events:\n🎯 Quizzes and intellectual games\n🎤 Karaoke nights\n🎉 Themed parties\n🎵 Music quizzes\n\nPlease select your language to continue:",
        "help": "📖 Bot Instructions:\n\n1️⃣ Use the '📅 Events' button to:\n   • Create new events\n   • View available events\n   • Manage your events\n\n2️⃣ When creating an event:\n   • Choose event type\n   • Set theme and description\n   • Specify date and location\n   • Set up teams (optional)\n\n3️⃣ Features:\n   • Join existing events\n   • Get notifications about upcoming events\n   • Weekly event digest\n\n❓ Need help? Just type 'help' or contact the administrator",
        "name_request": "Please enter your name:",
        "phone_request": "Please share your phone number using the button below:",
        "country_request": "Please enter your country (or skip by sending /skip):",
        "about_request": "Tell us about yourself (or skip by sending /skip):",
        "registration_complete": "Thank you for registering! You can now send messages to the administrator.",
        "message_received": "✅ Your message has been received. The administrator will reply soon.",
        "invalid_name": "Please enter a valid name (minimum 2 characters)",
        "invalid_phone": "Please share your phone number using the button below",
        "registration_required": "Please complete the registration first. Send /start to begin.",
        "skip_received": "Skipped",
        "error_occurred": "❌ An error occurred. Please try again later.",
        "start": "👋 Hello! Please select your language to continue.",
        "language_selected": "Language set to English. Please enter your real name:",
        "ask_phone": "Please share your phone number using the button below:",
        "ask_country": "Please enter your country:",
        "ask_about": "Tell us a little about yourself (or press /skip to skip this step):",
        "phone_received": "Thank you! Phone number saved.",
        "country_received": "Thank you! Country saved.",
        "about_received": "Thank you! Information saved.",
        "about_skipped": "Step skipped.",
        "broadcast_start": "Enter the message for broadcast:",
        "broadcast_confirm": "Please confirm the message:\n\n{text}\n\nSelect the target audience:",
        "broadcast_success": "Broadcast completed. Message sent to {count} users.",
        "broadcast_cancelled": "Broadcast cancelled.",
        "admin_reply_format": "To reply to a user, forward their message and add your response.",
        "user_not_registered": "Please complete the registration first to use this feature.",
        "events_menu": "📅 Events Menu - Choose an option:",
        "create_event": "Create a new event",
        "my_events": "My events",
        "available_events": "Available events",
        "event_create_title": "Please enter the event title:",
        "event_create_description": "Please enter the event description:",
        "event_create_location": "Please enter the event location:",
        "event_create_date": "Please enter the event date and time (format: DD.MM.YYYY HH:MM):",
        "event_create_max_participants": "Enter the maximum number of participants (or press /skip for unlimited):",
        "event_created": "Event created successfully!",
        "event_joined": "You have successfully joined the event!",
        "event_full": "Sorry, this event is already full.",
        "event_left": "You have left the event.",
        "event_cancelled": "Event has been cancelled.",
        "no_events_available": "No events available at the moment.",
        "no_my_events": "You don't have any events yet.",
        "invalid_date_format": "Invalid date format. Please use DD.MM.YYYY HH:MM",
        "payment_required": "Payment required to join this event",
        "payment_success": "✅ Payment successful! You have been added to the event participants.",
        "payment_error": "❌ Error processing payment. Please try again later.",
        "payment_cancelled": "Payment cancelled",
        "notification_event_soon": "🔔 Reminder: Event '{title}' starts in 24 hours!\n\nLocation: {location}",
        "notification_event_created": "New event created: {title}\n\nDate: {date}\nLocation: {location}",
        "notification_event_cancelled": "❌ Event '{title}' has been cancelled",
        "notification_payment_received": "💰 Payment received for event '{title}'",
        "weekly_digest_header": "📅 Upcoming events for the next week:",
        "event_price": "💰 Price: {price}",
        "event_free": "Free event",
        "event_participants_count": "👥 Participants: {count}",
        "event_max_participants": "Maximum participants: {count}",
        "event_date_time": "🕒 Date and time: {date}",
        "event_location": "📍 Location: {location}",
        "event_description": "📝 Description: {description}",
        "event_creator": "👤 Created by: {name}",
        "event_create_type": "Select event type:\n\n🎯 Quiz - Intellectual games\n🎤 Karaoke - Singing together\n🎉 Party - Themed parties\n🎵 Music Quiz - Test your music knowledge",
        "event_create_difficulty": "Select difficulty level for the quiz:\n\n😊 Easy\n🤔 Medium\n🧠 Hard",
        "event_create_music_genre": "Enter music genre(s) for the event (e.g., Rock, Pop, 90s):",
        "event_create_max_teams": "Enter maximum number of teams (or /skip):",
        "event_create_team_size": "Enter maximum team size (or /skip):",
        "event_create_theme": "Enter event theme (e.g., Movie Quiz, Rock Karaoke):",
        "invalid_event_type": "Please select a valid event type",
        "invalid_difficulty": "Please select a valid difficulty level",
        "past_events": "📜 Past Events",
        "no_past_events": "No past events found",
        "past_events_list": "📜 Past Events:\n\n",
    },
    "ru": {
        "welcome": "👋 Добро пожаловать в Meetupshare Bot!\n\nЭтот бот поможет вам организовать и участвовать в различных мероприятиях:\n🎯 Квизы и интеллектуальные игры\n🎤 Караоке вечера\n🎉 Тематические вечеринки\n🎵 Музыкальные квизы\n\nПожалуйста, выберите язык для продолжения:",
        "help": "📖 Инструкция по использованию бота:\n\n1️⃣ Используйте кнопку '📅 События' для:\n   • Создания новых мероприятий\n   • Просмотра доступных мероприятий\n   • Управления вашими мероприятиями\n\n2️⃣ При создании мероприятия:\n   • Выберите тип мероприятия\n   • Укажите тему и описание\n   • Укажите дату и место проведения\n   • Настройте команды (опционально)\n\n3️⃣ Возможности:\n   • Присоединяйтесь к существующим мероприятиям\n   • Получайте уведомления о предстоящих событиях\n   • Еженедельная рассылка мероприятий\n\n❓ Нужна помощь? Просто напишите 'помощь' или обратитесь к администратору",
        "name_request": "Пожалуйста, введите ваше имя:",
        "phone_request": "Пожалуйста, поделитесь номером телефона, нажав на кнопку ниже:",
        "country_request": "Пожалуйста, укажите вашу страну (или пропустите, отправив /skip):",
        "about_request": "Расскажите о себе (или пропустите, отправив /skip):",
        "registration_complete": "Спасибо за регистрацию! Теперь вы можете отправлять сообщения администратору.",
        "message_received": "✅ Ваше сообщение получено. Администратор ответит вам в ближайшее время.",
        "invalid_name": "Пожалуйста, введите корректное имя (минимум 2 символа)",
        "invalid_phone": "Пожалуйста, поделитесь номером телефона, используя кнопку ниже",
        "registration_required": "Пожалуйста, сначала завершите регистрацию. Отправьте /start, чтобы начать.",
        "skip_received": "Пропущено",
        "error_occurred": "❌ Произошла ошибка. Пожалуйста, попробуйте позже.",
        "start": "👋 Здравствуйте! Пожалуйста, выберите язык для продолжения.",
        "language_selected": "Язык установлен на русский. Пожалуйста, введите ваше настоящее имя:",
        "ask_phone": "Пожалуйста, поделитесь своим номером телефона, используя кнопку ниже:",
        "ask_country": "Пожалуйста, введите вашу страну:",
        "ask_about": "Расскажите немного о себе (или нажмите /skip, чтобы пропустить этот шаг):",
        "phone_received": "Спасибо! Номер телефона сохранен.",
        "country_received": "Спасибо! Страна сохранена.",
        "about_received": "Спасибо! Информация сохранена.",
        "about_skipped": "Шаг пропущен.",
        "broadcast_start": "Введите сообщение для рассылки:",
        "broadcast_confirm": "Пожалуйста, подтвердите сообщение:\n\n{text}\n\nВыберите целевую аудиторию:",
        "broadcast_success": "Рассылка завершена. Сообщение отправлено {count} пользователям.",
        "broadcast_cancelled": "Рассылка отменена.",
        "admin_reply_format": "Чтобы ответить пользователю, перешлите его сообщение и добавьте свой ответ.",
        "user_not_registered": "Пожалуйста, сначала завершите регистрацию, чтобы использовать эту функцию.",
        "events_menu": "📅 Меню событий - Выберите опцию:",
        "create_event": "Создать новое событие",
        "my_events": "Мои события",
        "available_events": "Доступные события",
        "event_create_title": "Пожалуйста, введите название события:",
        "event_create_description": "Пожалуйста, введите описание события:",
        "event_create_location": "Пожалуйста, введите место проведения события:",
        "event_create_date": "Пожалуйста, введите дату и время события (формат: ДД.ММ.ГГГГ ЧЧ:ММ):",
        "event_create_max_participants": "Введите максимальное количество участников (или нажмите /skip для неограниченного количества):",
        "event_created": "Событие успешно создано!",
        "event_joined": "Вы успешно присоединились к событию!",
        "event_full": "Извините, это событие уже заполнено.",
        "event_left": "Вы покинули событие.",
        "event_cancelled": "Событие было отменено.",
        "no_events_available": "В данный момент нет доступных событий.",
        "no_my_events": "У вас пока нет событий.",
        "invalid_date_format": "Неверный формат даты. Пожалуйста, используйте ДД.ММ.ГГГГ ЧЧ:ММ",
        "payment_required": "Для участия в событии требуется оплата",
        "payment_success": "✅ Оплата прошла успешно! Вы добавлены в список участников события.",
        "payment_error": "❌ Ошибка при обработке платежа. Пожалуйста, попробуйте позже.",
        "payment_cancelled": "Платеж отменен",
        "notification_event_soon": "🔔 Напоминание: Событие '{title}' начнется через 24 часа!\n\nМесто проведения: {location}",
        "notification_event_created": "Создано новое событие: {title}\n\nДата: {date}\nМесто: {location}",
        "notification_event_cancelled": "❌ Событие '{title}' было отменено",
        "notification_payment_received": "💰 Получена оплата за событие '{title}'",
        "weekly_digest_header": "📅 Предстоящие события на следующую неделю:",
        "event_price": "💰 Цена: {price}",
        "event_free": "Бесплатное событие",
        "event_participants_count": "👥 Участники: {count}",
        "event_max_participants": "Максимум участников: {count}",
        "event_date_time": "🕒 Дата и время: {date}",
        "event_location": "📍 Место проведения: {location}",
        "event_description": "📝 Описание: {description}",
        "event_creator": "👤 Создатель: {name}",
        "event_create_type": "Выберите тип мероприятия:\n\n🎯 Квиз - Интеллектуальные игры\n🎤 Караоке - Поём вместе\n🎉 Вечеринка - Тематические встречи\n🎵 Музыкальный квиз - Проверь свои знания музыки",
        "event_create_difficulty": "Выберите уровень сложности для квиза:\n\n😊 Лёгкий\n🤔 Средний\n🧠 Сложный",
        "event_create_music_genre": "Введите музыкальный жанр(ы) для мероприятия (например, Рок, Поп, 90-е):",
        "event_create_max_teams": "Введите максимальное количество команд (или /skip):",
        "event_create_team_size": "Введите максимальный размер команды (или /skip):",
        "event_create_theme": "Введите тему мероприятия (например, Кино-квиз, Рок караоке):",
        "invalid_event_type": "Пожалуйста, выберите корректный тип мероприятия",
        "invalid_difficulty": "Пожалуйста, выберите корректный уровень сложности",
        "past_events": "📜 Прошедшие события",
        "no_past_events": "Прошедших событий не найдено",
        "past_events_list": "📜 Прошедшие события:\n\n",
    }
}

def get_text(key: str, language: str) -> str:
    return TEXTS.get(language, TEXTS["en"]).get(key, TEXTS["en"][key]) 